config/routes.rb
Blog::Application.routes.draw do
  resources :articles
  match "search" => "search#search", as: :search, via: [:get, :post]

  resources :articles do
    resources :posts
  end

  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
require 'elasticsearch/model'

class Article < ApplicationRecord
  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks
  # searchkick
  searchkick word_start: [:title], highlight: [:title]
  # searchkick autocomplete: [:title]
  # searchkick  highlight: [:title]

  has_many :posts,  dependent: :destroy
  validates :title, presence: true, uniqueness: true

  # def self.search(query)
  #   __elasticsearch__.search(
  #     {
  #       query: {
  #         multi_match: {
  #           query: query&.first,
  #           fields: ['title^10', 'text']
  #         }
  #       }
  #     }
  #   )
  # end
  # settings index: { number_of_shards: 1 } do
  #   mappings dynamic: 'false' do
  #     indexes :title, analyzer: 'english'
  #     indexes :text, analyzer: 'english'
  #   end
  # end
  # Article.__elasticsearch__.create_index!
  # Article.import # for auto sync model with elastic search
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])   
  end

  def new
  end

  def edit
    @article = Article.find(params[:id])  
  end

  def create
    @article = Article.new article_params
    if @article.valid?
      @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      # flash.now[:notice] =  @article.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def destroy
    @article = Article.destroy(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_article

  def create
    @post = @article.posts.create(post_params)
  end

  def destroy
    @post = @article.posts.find(params[:id])
    @post.destroy
  end

  private

  def get_article
    @article = Article.find(params[:article_id])
  end

  def post_params
    params.require(:post).permit(:body, :article_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @articles = []
    else
      @articles = Article.search params[:q], match: :word_start, highlight: true
      @articles= @articles.with_highlights
    end
    params.delete :q
  end

  def autocomplete
    render json: Article.search(params[:q], {
      fields: ["title"],
      limit: 10
      }).map(&:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/articles/_all.html.erb
<% for post in @article.posts  %>
  <ul>
   <li class="post">
      <%= post.body %>
      <%= button_tag "Remove Post", data: { controller: "posts", action: "posts#remove" } %>
      <%= button_tag "Upvote Post", data: { controller: "posts", action: "posts#upvote" } %>
    </li>
  </ul>
<% end %>

app/views/articles/_last_post.html.erb
<ul data-posts-target="add">
  <li class="post">
    <%= @article&.posts&.last&.body %>
  </li>
</ul>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<div data-controller="articles" 
    data-action="item:add->articles#refreshTotal"
     data-articles-counter="0">
  <%= form_for :article, url: articles_path, data: {action: "articles#addbody"} do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, 'data-target' => "articles.title", 'data-action' => 'keyup->articles#countCharacters' %>
      Characters: <span data-target='articles.counter'><%= @article&.title&.to_s&.size %></span>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>

  <%= link_to '<- Back', articles_path %>


  <button data-controller="item" data-action="item#add">
    Add
  </button>

  <div>
    <span>No of items : </span>
    <span data-articles-target="counterView">0</span>
  </div>
</div>
    

    

app/views/articles/index.html.erb
<h1> Articles </h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= button_to 'Show', article_path(:id => article.id), :method => :get %></td>
        <td><%= button_to 'Edit', edit_article_path(:id => article.id), :method => :get %></td>
        <td><%= button_to 'Destroy', article_path(:id => article.id), :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<style type="text/css">  
  .button {
    content:attr(data-hover);
    background-color: #d2322d;
    display: inline-block;
    padding: 6px 12px;
    border-radius: 4px;
    color:#fff;
    margin-right:10px;
    margin: 10px 10px;
  }
</style>  

app/views/articles/new.html.erb
<h1>New Article</h1>
<div data-controller="articles">
  <%= form_for :article, url: articles_path, data: {action: "articles#addbody"} do |f| %>

    <% if not @article.nil? and @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <p>
      <%= flash[:notice] %><br>
    </p>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, 'data-articles-target' => "title", 'data-action' => 'keyup->articles#countCharacters' %>
      Characters: <span data-articles-target='counter'><%= @article&.title&.to_s&.size %></span>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>

  <%= link_to '<- Back', articles_path %>
</div>
    

    

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article&.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article&.text %>
</p>

<h2>Posts</h2>

<div data-controller="posts">
  <%= form_tag article_posts_path(@article.id), method: :post do %>
    <label>Post title:</label><br>
    <textarea id="post_title" name="post[body]" data-posts-target="body" ></textarea><br>

    <input type="submit" value="Submit Post" data-action="posts#addBody">
  <% end %>


  <%= render 'articles/last_post' %>


  <%= link_to '<- Back', articles_path %>

  <button data-action="posts#showAll">Show Older Posts</button>

  <div data-posts-target="show" style="visibility:hidden">
    <%= render 'articles/all' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<%= form_for :post, url: article_posts_path do |f| %>
  <p>
    <h2>Title</h2>
    <h3><%= @article.title %></h3>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to '<- Back', articles_path %>

app/views/search/search.html.erb
<h1>Articles Search</h1>

<%= form_for search_path, method: :post do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @articles.each do |article, highlights| %>
    <li>
      <h3>
        <%= link_to(raw(highlights[:title]) , controller: "articles", action: "show" , id: article.id) %>
      </h3>
    </li>
  <% end %>
</ul>

app/views/sharks/_all.html.erb
<% for post in @article.posts  %>
  <ul>
   <li class="post">
      <%= post.body %>
      <%= button_tag "Remove Post", data: { controller: "posts", action: "posts#remove" } %>
      <%= button_tag "Upvote Post", data: { controller: "posts", action: "posts#upvote" } %>
    </li>
  </ul>
<% end %>

app/views/sharks/_post.html.erb
<div data-controller="posts">
  <%= form_with model: [@article, @article.posts.build], data: { action: "posts#addBody" } do |form| %>
    <%= form.text_area :body, placeholder: "Your post here", data: { target: "posts.body" } %>
    <br>
    <%= form.submit %>
  <% end %>

  <ul data-target="posts.add">
  </ul>

</div>

app/views/sharks/index.html.erb
<tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= button_to 'Show', article_path(:id => article.id), :method => :get %></td>
        <td><%= button_to 'Edit', edit_article_path(:id => article.id), :method => :get %></td>
        <td><%= button_to 'Destroy', article_path(:id => article.id), :method => :delete %></td>
      </tr>
    <% end %>
</tbody>

app/views/sharks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Facts:</strong>
  <%= @article.text %>
</p>

<h2>Posts</h2>
<%= render 'articles/posts' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<div data-controller="posts">
  <button data-action="posts#showAll">Show Older Posts</button>

  <div data-target="posts.show" style="visibility:hidden">
    <%= render 'articles/all' %>
  </div>
</div>